### PR TITLE
Info about bugs + client contact

### PR DESCRIPTION
**Pull request by sofer**

### CODE REVIEW

**Comment by sofer** [comment]
See https://github.com/foundersandcoders/mvps/issues/4

**Comment by iteles** [comment]
@sofer There was some discussion about including the `scope` and `rates` section from the original letter of engagement into this contract. I feel like this is part of #4 as well. Are you thinking this will be done in a separate PR?

**Comment by sofer** [comment]
@iteles I have added an explicit reference to the developer rates. The scope (*Minimum set of deliverables*) would be added to the bottom of each agreement.

**Comment by iteles** [comment]
Got it, all clear now! :+1:

**Pull request merged**
